### ISSUE TITLE
Ubuntu 22.04 x64如何使用?

### ISSUE THREAD

**Issue by JadynWong** [sdcb/OpenVINO.NET#13]
- OS: Ubuntu 22.04.3 LTS (WSL2 x64) / mcr.microsoft.com/dotnet/aspnet:8.0.0-jammy

我想在容器中使用这个库, 之前用的PaddleSharp, 需要自己构建aspnetcore8.0.0带opencv和paddle的镜像. 
这个库看起来提供了大部分系统的runtime, 在Windows上工作正常, 但是Ubuntu22.04测试无法启动, 看log是OpenVINO runtime无法加载, 是需要额外配置吗?

Demo.csproj: 
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup Condition=" '$(OS)' == 'Windows_NT' ">
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.8.0.20230708" />
    <PackageReference Include="Sdcb.OpenVINO.runtime.win-x64" Version="2023.2.0" />
  </ItemGroup>

  <ItemGroup Condition=" '$(OS)' != 'Windows_NT' ">
    <PackageReference Include="Sdcb.OpenCvSharp4.mini.runtime.ubuntu.22.04-x64" Version="4.8.0.20231125" />
    <PackageReference Include="Sdcb.OpenVINO.runtime.ubuntu.22.04-x64" Version="2023.2.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Sdcb.OpenVINO" Version="0.6.1" />
    <PackageReference Include="Sdcb.OpenVINO.PaddleOCR.Models.Online" Version="0.2.1" />
    <PackageReference Include="Sdcb.OpenVINO.PaddleOCR" Version="0.6.2" />
  </ItemGroup>

</Project>
```
Program.cs
```csharp
using OpenCvSharp;
using Sdcb.OpenVINO.PaddleOCR;
using Sdcb.OpenVINO.PaddleOCR.Models.Online;

var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

var model = await OnlineFullModels.ChineseV4.DownloadAsync();

var paddleOcrAll = new PaddleOcrAll(model)
{
    Enable180Classification = true,
    AllowRotateDetection = true,
};

app.MapGet("/ocr", async () =>
{
    using Mat src = Cv2.ImDecode(await new HttpClient().GetByteArrayAsync("https://io.starworks.cc:88/paddlesharp/ocr/samples/xdr5450.webp"), ImreadModes.Color);
    var result = paddleOcrAll.Run(src);
    return result;
});

app.Run();
```

dotnet run
```log
Building...
/usr/share/dotnet/sdk/8.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(284,5): warning NETSDK1206: Found version-specific or distribution-specific runtime identifier(s): ubuntu.22.04-x64. Affected libraries: Sdcb.OpenCvSharp4.mini.runtime.ubuntu.22.04-x64. In .NET 8.0 and higher, assets for version-specific and distribution-specific runtime identifiers will not be found by default. See https://aka.ms/dotnet/rid-usage for details. [/mnt/d/demo/OpenVINO_Demo/OpenVINO_Demo.csproj]
Downloading ch_PP-OCRv4_det model from https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_det_infer.tar
Extracting paddleocr-models/ch_PP-OCRv4_det/ch_PP-OCRv4_det_infer.tar to paddleocr-models/ch_PP-OCRv4_det
Downloading ch_ppocr_mobile_v2.0_cls model from https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_cls_infer.tar
Extracting paddleocr-models/ch_ppocr_mobile_v2.0_cls/ch_ppocr_mobile_v2.0_cls_infer.tar to paddleocr-models/ch_ppocr_mobile_v2.0_cls
Downloading ch_PP-OCRv4_rec model from https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_rec_infer.tar
Extracting paddleocr-models/ch_PP-OCRv4_rec/ch_PP-OCRv4_rec_infer.tar to paddleocr-models/ch_PP-OCRv4_rec
Unhandled exception. System.TypeInitializationException: The type initializer for 'Sdcb.OpenVINO.Natives.NativeMethods' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Sdcb.OpenVINO.Natives.OpenVINOLibraryLoader' threw an exception.
 ---> System.DllNotFoundException: Unable to load native library: libopenvino_c.so.2320, dependencies status:
libtbb.so.12:0
libopenvino.so.2320:0
Unable to load native library: libopenvino_c.so.2310, dependencies status:
libtbb.so.12:0
libopenvino.so.2310:0

   at Sdcb.OpenVINO.Natives.OpenVINOLibraryLoader.LoadWithDeps(Assembly assembly, Nullable`1 searchPath, LibDeps[] libDeps)
   at Sdcb.OpenVINO.Natives.OpenVINOLibraryLoader.OpenVINOImportResolver(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at Sdcb.OpenVINO.Natives.NativeMethods.ov_get_openvino_version(ov_version* version)
   at Sdcb.OpenVINO.OVCore.get_Version()
   at Sdcb.OpenVINO.Natives.OpenVINOLibraryLoader..cctor()
   --- End of inner exception stack trace ---
   at Sdcb.OpenVINO.Natives.OpenVINOLibraryLoader.Init()
   at Sdcb.OpenVINO.Natives.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at Sdcb.OpenVINO.Natives.NativeMethods.ov_core_create(ov_core** core)
   at Sdcb.OpenVINO.OVCore.CreateHandle()
   at Sdcb.OpenVINO.OVCore..ctor()
   at Sdcb.OpenVINO.OVCore.<>c.<.cctor>b__24_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Sdcb.OpenVINO.OVCore.get_Shared()
   at Sdcb.OpenVINO.DeviceOptions.DefaultCreateOVCore()
   at Sdcb.OpenVINO.BaseModel.CreateCompiledModel(DeviceOptions options, Action`1 afterReadModel, Action`2 prePostProcessing, Action`1 afterBuildModel, Action`1 afterCompiledModel)
   at Sdcb.OpenVINO.PaddleOCR.PaddleOcrDetector..ctor(DetectionModel model, DeviceOptions options, Nullable`1 staticShapeSize)
   at Sdcb.OpenVINO.PaddleOCR.PaddleOcrAll..ctor(FullOcrModel model, PaddleOcrOptions options)
   at Sdcb.OpenVINO.PaddleOCR.PaddleOcrAll..ctor(FullOcrModel model, DeviceOptions device)
   at Program.<Main>$(String[] args) in /mnt/d/demo/OpenVINO_Demo/Program.cs:line 10
   at Program.<Main>(String[] args)
```

**Comment by DragonFlyEast** [comment]
运行 ldd libopenvino_c.so.2310 看看缺少啥

**Comment by JadynWong** [comment]
> 运行 ldd libopenvino_c.so.2310 看看缺少啥

感谢, 已解决.

`ldd libopenvino.so.2320`
```sh
linux-vdso.so.1 (0x00007fffeb7dc000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007feab739d000)
libtbb.so.2 => not found
libatomic.so.1 => not found
libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007feab7171000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007feab708a000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007feab7068000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007feab7063000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007feab6e3b000)
/lib64/ld-linux-x86-64.so.2 (0x00007feab87a9000)
```

安装 `libtbb2` , `libatomic1` 后运行正常
```bash
sudo apt-get install -y --no-install-recommends libtbb2 libatomic1
```
