### ISSUE TITLE
The problem is on the server with OS Windows Server 2016 

### ISSUE THREAD

**Issue by aropb** [sdcb/OpenVINO.NET#14]
Hi,

I really liked your product. It runs fast on Windows 10 and Linux Debian. But it doesn't run on Windows Server 2016.
I really hope for a solution to the problem.

Thanks.

Errors:

1. Error in System log:

    Faulting module name: tbbbind_2_5.dll, version: 2021.2.2.0, time stamp: 0x6454504a
Exception code: 0xc0000005
Fault offset: 0x0000000000002c2b

3. I removed tbbbind* DLLs:

      The type initializer for 'Sdcb.OpenVINO.Natives.NativeMethods' threw an exception.
      System.TypeInitializationException: The type initializer for 'Sdcb.OpenVINO.Natives.NativeMethods' threw an exception.
       ---> System.TypeInitializationException: The type initializer for 'Sdcb.OpenVINO.Natives.OpenVINOLibraryLoader' threw an exception.
       ---> System.DllNotFoundException: Unable to load native library: openvino_c.dll, dependencies status:
      openvino.dll:0

         at Sdcb.OpenVINO.Natives.OpenVINOLibraryLoader.LoadWithDeps(Assembly assembly, Nullable`1 searchPath, LibDeps[] libDeps)
         at Sdcb.OpenVINO.Natives.OpenVINOLibraryLoader.OpenVINOImportResolver(String libraryName, Assembly assembly, Nullable`1 searchPath)
         at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
         at Sdcb.OpenVINO.Natives.NativeMethods.ov_get_openvino_version(ov_version* version)
         at Sdcb.OpenVINO.OVCore.get_Version()
         at Sdcb.OpenVINO.Natives.OpenVINOLibraryLoader..cctor()
         --- End of inner exception stack trace ---
         at Sdcb.OpenVINO.Natives.OpenVINOLibraryLoader.Init()
         at Sdcb.OpenVINO.Natives.NativeMethods..cctor()
         --- End of inner exception stack trace ---
         at Sdcb.OpenVINO.Natives.NativeMethods.ov_core_create(ov_core** core)
         at Sdcb.OpenVINO.OVCore.CreateHandle()
         at Sdcb.OpenVINO.OVCore..ctor()
         at Sdcb.OpenVINO.OVCore.<>c.<.cctor>b__24_0()
         at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
         at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
         at System.Lazy`1.CreateValue()
         at Sdcb.OpenVINO.OVCore.get_Shared()
         at Sdcb.OpenVINO.DeviceOptions.DefaultCreateOVCore()
         at Sdcb.OpenVINO.BaseModel.CreateCompiledModel(DeviceOptions options, Action`1 afterReadModel, Action`2 prePostProcessing, Action`1 afterBuildModel, Action`1 afterCompiledModel)
         at Sdcb.OpenVINO.PaddleOCR.PaddleOcrRecognizer..ctor(RecognizationModel model, DeviceOptions deviceOptions, Nullable`1 staticShapeWidth)
         at (RecognizationModel, DeviceOptions, Nullable`1)
         at ???????????.???????????(RecognizationModel, DeviceOptions, Nullable`1)
         at WebAccountServer.Utils.OcrEngine..ctor(String publishDirectory)
         at (String)
         at ???????????.???????????(String)
         at WebAccountServer.Program.Init(Boolean isService, String[] args)
         at WebAccountServer.Program.Main(String[] args)
         at ???????????.???????????(TaskAwaiter&)
         at WebAccountServer.Program.<Main>(String[] args)
Unhandled exception. System.TypeInitializationException: The type initializer for 'Sdcb.OpenVINO.Natives.NativeMethods' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Sdcb.OpenVINO.Natives.OpenVINOLibraryLoader' threw an exception.
 ---> System.DllNotFoundException: Unable to load native library: openvino_c.dll, dependencies status:
openvino.dll:0
   at Sdcb.OpenVINO.Natives.OpenVINOLibraryLoader.LoadWithDeps(Assembly assembly, Nullable`1 searchPath, LibDeps[] libDeps)
   at Sdcb.OpenVINO.Natives.OpenVINOLibraryLoader.OpenVINOImportResolver(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at Sdcb.OpenVINO.Natives.NativeMethods.ov_get_openvino_version(ov_version* version)
   at Sdcb.OpenVINO.OVCore.get_Version()
   at Sdcb.OpenVINO.Natives.OpenVINOLibraryLoader..cctor()
   --- End of inner exception stack trace ---
   at Sdcb.OpenVINO.Natives.OpenVINOLibraryLoader.Init()
   at Sdcb.OpenVINO.Natives.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at Sdcb.OpenVINO.Natives.NativeMethods.ov_core_create(ov_core** core)
   at Sdcb.OpenVINO.OVCore.CreateHandle()
   at Sdcb.OpenVINO.OVCore..ctor()
   at Sdcb.OpenVINO.OVCore.<>c.<.cctor>b__24_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Sdcb.OpenVINO.OVCore.get_Shared()
   at Sdcb.OpenVINO.DeviceOptions.DefaultCreateOVCore()
   at Sdcb.OpenVINO.BaseModel.CreateCompiledModel(DeviceOptions options, Action`1 afterReadModel, Action`2 prePostProcessing, Action`1 afterBuildModel, Action`1 afterCompiledModel)
   at Sdcb.OpenVINO.PaddleOCR.PaddleOcrRecognizer..ctor(RecognizationModel model, DeviceOptions deviceOptions, Nullable`1 staticShapeWidth)

**Comment by aropb** [comment]
Your PaddleSharp is running on Windows Server at the same time.

**Comment by AvenSun** [comment]
You can use [Dependency Walker](https://www.dependencywalker.com/) to inspect whether the dependencies of **openvino_c.dll** are normal.

**Comment by aropb** [comment]
Unfortunately, I am not a system engineer, it will be difficult for me to understand what the problem is and find a solution. That's why I wrote here. I spent all day yesterday trying to find the requirements for running VINO on Windows Server or known issues. I didn't find anything. The official website is empty. I only see that VINO should work on Windows Server in principle. I only need to use the CPU. I have enabled CPU usage. I ask you, as a pro in this matter, to help me understand what the problem may be. Thank you.

**Comment by AvenSun** [comment]
DW is straightforward to use. simply drag the **openvino_c.dll** and **openvino.dll** onto DW,
then check if any dynamic libraries are marked in yellow by DW.
It might be looks like the attached image below.

![dw](https://github.com/sdcb/OpenVINO.NET/assets/5615543/459ad706-78a0-4c13-a478-e8ae94c32987)

**Comment by aropb** [comment]
Thanks, I'll try. 
Another question: if I will definitely use only the CPU, can I exclude unnecessary DLL files from the project?

Am I enabling CPU usage correctly?

var ocr = new PaddleOcrRecognizer(new FileRecognizationModel(ocrPath + "english", ocrPath + "en_dict.txt", ModelVersion.V3), new Sdcb.OpenVINO.DeviceOptions("CPU"));

**Comment by sdcb** [comment]
Have you installed vcredist2015-2022 on your WS2016? https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by aropb** [comment]
Yes, PaddleSharp is working on the same server

**Comment by aropb** [comment]
> You can use [Dependency Walker](https://www.dependencywalker.com/) to inspect whether the dependencies of **openvino_c.dll** are normal.

[dwi.zip](https://github.com/sdcb/OpenVINO.NET/files/13766333/dwi.zip)

Please help me understand what is missing.
Thanks.

**Comment by aropb** [comment]
The most interesting thing is that I have OpenVINO running on Windows 10, but DW shows errors:
![image](https://github.com/sdcb/OpenVINO.NET/assets/2377913/5755f104-69b9-4ccd-ae8e-3d08211bb728)

**Comment by sdcb** [comment]
can you try again with https://github.com/lucasg/Dependencies
this one should works better

**Comment by aropb** [comment]
This utility shows me problems, although everything is working.

![image](https://github.com/sdcb/OpenVINO.NET/assets/2377913/eecb9d16-607b-45bb-a8db-d05ada7830f6)

![image](https://github.com/sdcb/OpenVINO.NET/assets/2377913/a7ffbfd9-a4e7-4cec-a708-472251933e70)

**Comment by aropb** [comment]
The same thing on Windows Server where it does not work, DW no longer shows errors:

![Screenshot 2023-12-27 151359](https://github.com/sdcb/OpenVINO.NET/assets/2377913/5e9a402e-608c-47c3-87a2-29422eabe7eb)

![Screenshot 2023-12-27 151418](https://github.com/sdcb/OpenVINO.NET/assets/2377913/c0fbcdc1-8b02-4b45-b82b-3dfc7cd1ce1e)

**Comment by aropb** [comment]
I found how to do it, it didn't help
